spring:
  application:
    name: com.feng.http
  main:
    banner-mode: "off"
  profiles:
    active: "http"
http:
  maxTotal: 20
  defaultMaxPerRoute: 5
  connectTimeout: 1000
  connectionRequestTimeout: 500
  socketTimeout: 10000
  staleConnectionCheckEnabled: true
server:
  port: 8087
  servlet:
    context-path: /